language: android

sudo: false

jdk:
  - oraclejdk8

android:
  components:
    # Use the latest revision of Android SDK Tools
    - platform-tools
    - tools

    # The BuildTools version used by your project
    - build-tools-24.0.2

    # The SDK version used to compile your project
    - android-24

    # Additional components
    - extra
    - addon

script:
  ./gradlew build
